version: '3.8'

services:
  # Database Services - Using PostgreSQL 13 for better compatibility
  postgres:
    image: postgres:13-alpine
    container_name: ai-platform-postgres
    environment:
      POSTGRES_DB: ai_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Ensure proper encoding and locale
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      # Trust local connections for easier development
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
      - ./scripts/init-contest-db.sql:/docker-entrypoint-initdb.d/02-init-contest-db.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d ai_platform']
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
    restart: unless-stopped
    # Add some performance settings for development
    command: >
      postgres
      -c shared_preload_libraries=''
      -c max_connections=200
      -c shared_buffers=128MB
      -c effective_cache_size=256MB
      -c maintenance_work_mem=32MB
      -c checkpoint_completion_target=0.7
      -c wal_buffers=4MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200

  mongodb:
    image: mongo:6-jammy
    container_name: ai-platform-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
      MONGO_INITDB_DATABASE: ai_platform
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ai-platform-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Message Queue
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ai-platform-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672' # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Monitoring and Observability
  prometheus:
    image: prom/prometheus:latest
    container_name: ai-platform-prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: ai-platform-grafana
    ports:
      - '3001:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    restart: unless-stopped

  # Development Tools
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ai-platform-mailhog
    ports:
      - '1025:1025' # SMTP
      - '8025:8025' # Web UI
    restart: unless-stopped

  # Code Execution Environment
  code-runner:
    image: node:18-alpine
    container_name: ai-platform-code-runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: tail -f /dev/null
    privileged: true
    restart: unless-stopped

  # Application Services
  api-gateway:
    build: ./services/api-gateway
    container_name: ai-platform-api-gateway
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - PORT=8080
      - USER_SERVICE_URL=http://user-service:3006
      - PROBLEM_SERVICE_URL=http://problem-service:3002
      - EXECUTION_SERVICE_URL=http://code-execution-service:3004
      - AI_SERVICE_URL=http://ai-analysis-service:8001
      - CONTEST_SERVICE_URL=http://contest-service:3003
      - ANALYTICS_SERVICE_URL=http://analytics-service:3005
      - NOTIFICATION_SERVICE_URL=http://notification-service:3007
      - REALTIME_SERVICE_URL=http://realtime-service:3008
      - REDIS_HOST=redis
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - ai-platform-network

  user-service:
    build: ./services/user-service
    container_name: ai-platform-user-service
    ports:
      - '3006:3006'
    environment:
      - NODE_ENV=development
      - PORT=3006
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ai_platform
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - ai-platform-network

  problem-service:
    build: ./services/problem-service
    container_name: ai-platform-problem-service
    ports:
      - '3002:3002'
    environment:
      - NODE_ENV=development
      - PORT=3002
      - MONGODB_URL=mongodb://mongo:mongo@mongodb:27017/ai_platform
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - ai-platform-network

  contest-service:
    build: ./services/contest-service
    container_name: ai-platform-contest-service
    ports:
      - '3003:3003'
    environment:
      - NODE_ENV=development
      - PORT=3003
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ai_platform
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - ai-platform-network

  code-execution-service:
    build: ./services/code-execution-service
    container_name: ai-platform-code-execution-service
    ports:
      - '3004:3004'
    environment:
      - PORT=3004
      - REDIS_URL=redis://redis:6379
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    privileged: true
    restart: unless-stopped
    networks:
      - ai-platform-network

  analytics-service:
    build: ./services/analytics-service
    container_name: ai-platform-analytics-service
    ports:
      - '3005:3005'
    environment:
      - NODE_ENV=development
      - PORT=3005
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/ai_platform
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - ai-platform-network

  notification-service:
    build: ./services/notification-service
    container_name: ai-platform-notification-service
    ports:
      - '3007:3007'
    environment:
      - NODE_ENV=development
      - PORT=3007
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - redis
      - mailhog
    restart: unless-stopped
    networks:
      - ai-platform-network

  realtime-service:
    build: ./services/realtime-service
    container_name: ai-platform-realtime-service
    ports:
      - '3008:3008'
    environment:
      - NODE_ENV=development
      - PORT=3008
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - ai-platform-network

  ai-analysis-service:
    build: ./services/ai-analysis-service
    container_name: ai-platform-ai-analysis-service
    ports:
      - '8001:8001'
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@postgres:5432/ai_platform
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - ai-platform-network

  frontend:
    build: ./apps/frontend
    container_name: ai-platform-frontend
    ports:
      - '3000:3000'
    environment:
      - VITE_API_BASE_URL=http://localhost:8080/api
      - VITE_SOCKET_URL=http://localhost:3008
    depends_on:
      - api-gateway
    restart: unless-stopped
    networks:
      - ai-platform-network

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:

networks:
  ai-platform-network:
    driver: bridge