apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-analysis-service
  namespace: ai-coding-platform
  labels:
    app: ai-analysis-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-analysis-service
  template:
    metadata:
      labels:
        app: ai-analysis-service
        version: v1
    spec:
      containers:
      - name: ai-analysis-service
        image: ai-coding-platform/ai-analysis-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: PORT
          value: "8001"
        envFrom:
        - configMapRef:
            name: app-config
        - configMapRef:
            name: database-config
        - secretRef:
            name: app-secrets
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: ai-analysis-service
  namespace: ai-coding-platform
  labels:
    app: ai-analysis-service
spec:
  selector:
    app: ai-analysis-service
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-analysis-service-hpa
  namespace: ai-coding-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-analysis-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75