apiVersion: v1
kind: ServiceMonitor
metadata:
  name: ai-coding-platform-metrics
  namespace: ai-coding-platform
  labels:
    app: ai-coding-platform
spec:
  selector:
    matchLabels:
      metrics: enabled
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-custom-hpa
  namespace: ai-coding-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  - type: Pods
    pods:
      metric:
        name: http_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  - type: Pods
    pods:
      metric:
        name: response_time_p95
      target:
        type: AverageValue
        averageValue: "200m"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Min
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: code-execution-custom-hpa
  namespace: ai-coding-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: code-execution-service
  minReplicas: 3
  maxReplicas: 50
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  - type: Pods
    pods:
      metric:
        name: execution_queue_length
      target:
        type: AverageValue
        averageValue: "5"
  - type: Pods
    pods:
      metric:
        name: active_executions
      target:
        type: AverageValue
        averageValue: "10"
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 200
        periodSeconds: 30
      - type: Pods
        value: 5
        periodSeconds: 30
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
      selectPolicy: Min
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: code-execution-queue-scaler
  namespace: ai-coding-platform
spec:
  scaleTargetRef:
    name: code-execution-service
  minReplicaCount: 3
  maxReplicaCount: 100
  triggers:
  - type: redis
    metadata:
      address: redis-service:6379
      listName: execution_queue
      listLength: "5"
      passwordFromEnv: REDIS_PASSWORD
  - type: prometheus
    metadata:
      serverAddress: http://prometheus:9090
      metricName: execution_response_time_p95
      threshold: "5000"
      query: histogram_quantile(0.95, rate(execution_duration_seconds_bucket[5m]))
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: ai-coding-platform-rules
  namespace: ai-coding-platform
  labels:
    prometheus: kube-prometheus
    role: alert-rules
spec:
  groups:
  - name: ai-coding-platform.rules
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High error rate detected"
        description: "Error rate is above 5% for {{ $labels.service }}"
    
    - alert: HighResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High response time detected"
        description: "95th percentile response time is above 1s for {{ $labels.service }}"
    
    - alert: CodeExecutionQueueBacklog
      expr: redis_list_length{list="execution_queue"} > 50
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Code execution queue backlog"
        description: "Execution queue has {{ $value }} pending jobs"
    
    - alert: DatabaseConnectionsHigh
      expr: pg_stat_activity_count > 80
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "High database connections"
        description: "PostgreSQL has {{ $value }} active connections"