global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # API Gateway
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['host.docker.internal:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # User Service
  - job_name: 'user-service'
    static_configs:
      - targets: ['host.docker.internal:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Problem Service
  - job_name: 'problem-service'
    static_configs:
      - targets: ['host.docker.internal:3003']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Code Execution Service
  - job_name: 'code-execution-service'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # AI Analysis Service
  - job_name: 'ai-analysis-service'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Contest Service
  - job_name: 'contest-service'
    static_configs:
      - targets: ['host.docker.internal:3004']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Real-time Service
  - job_name: 'realtime-service'
    static_configs:
      - targets: ['host.docker.internal:3005']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Analytics Service
  - job_name: 'analytics-service'
    static_configs:
      - targets: ['host.docker.internal:3006']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Notification Service
  - job_name: 'notification-service'
    static_configs:
      - targets: ['host.docker.internal:3007']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Health checks
  - job_name: 'health-checks'
    static_configs:
      - targets: 
        - 'host.docker.internal:3001'
        - 'host.docker.internal:3002'
        - 'host.docker.internal:3003'
        - 'host.docker.internal:3004'
        - 'host.docker.internal:3005'
        - 'host.docker.internal:3006'
        - 'host.docker.internal:3007'
        - 'host.docker.internal:8001'
        - 'host.docker.internal:8002'
    metrics_path: '/health'
    scrape_interval: 30s